- id: nbstripout-preserve-timestamp
  name: nbstripout (preserve timestamp)
  entry: nbstripout-preserve-timestamp
  language: python
  types: [jupyter]
  additional_dependencies: [nbstripout]

- id: jupytext-enforce-pairing
  name: jupytext (enforce pairing)
  entry: jupytext-enforce-pairing
  language: python
  types: [jupyter]
  additional_dependencies: [jupytext]

- id: jupytext-smart-sync
  name: jupytext (smart sync)
  entry: jupytext-smart-sync
  language: python
  types_or: [jupyter, python]
  additional_dependencies: [jupytext]
