[project]
name = "pre_commit_hooks"
version = "0.1.1"
description = "A library of custom `pre-commit-hooks` used in other projects"
authors = [{ name = "Nesta" }]
license = { text = "MIT" }
readme = "README.md"
requires-python = "==3.13.*"
dependencies = ["jupytext>=1.17.2", "nbstripout>=0.8.1"]

[project.urls]
repository = "https://github.com/nestauk/pre-commit-hooks"
issues = "https://github.com/nestauk/pre-commit-hooks/issues"

[dependency-groups]
dev = ["ipykernel", "ruff"]

[tool.ruff]
line-length = 120

[tool.ruff.lint]
select = [
    "ANN", # flake8-annotations
    "B",   # flake8-bugbear: Likely bugs
    "C",   # flake8-comprehensions and mccabe complexity
    "D",   # pydocstyle: Docstring conventions
    "E",   # pycodestyle: Errors (default)
    "F",   # pyflakes: Linter
    "I",   # isort
    "N",   # pep8-naming: Naming conventions
    "W",   # pycodestyle: Warnings (default)
]
ignore = [
    "D100", # Warns about missing module-level docstrings
    "S101", # Warns about assert being removed when compiled
]

[tool.ruff.lint.isort]
known-first-party = ["pre_commit_hooks"]

[tool.ruff.lint.pydocstyle]
convention = "google"

[tool.ruff.lint.per-file-ignores]
"__init__.py" = ["F401", "E402", "D104"]

[tool.ruff.format]
docstring-code-format = true
docstring-code-line-length = "dynamic"
